// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"flex items-center justify-end\"><a href=\"/api/users/logout\">Logout</a></nav><main x-data=\"{messages: []}\"><div class=\"flex items-center justify-center\"><div><input type=\"text\" name=\"roomName\" id=\"roomName\" placeholder=\"roomName\" class=\"block text-xl bg-transparent mb-5\"> <button @click=\"createAndConnect(messages)\" class=\"block text-xl m-auto\">Create and Join</button></div><div><input type=\"text\" name=\"roomId\" id=\"roomId\" placeholder=\"roomId\" class=\"block text-xl bg-transparent mb-5\"> <button @click=\"connect(messages)\" class=\"block text-xl m-auto\">Join</button></div></div><hr><div x-data=\"{content: &#39;&#39;}\"><h2 class=\"text-center\">Chat</h2><form><input type=\"text\" x-model=\"content\" placeholder=\"content\"> <input type=\"submit\" value=\"Enter\" onclick=\"console.log(&#39;submit&#39;)\"></form><template x-for=\"message in messages\"><div><div>Username: <span x-text=\"message.username\"></span></div><div>Content: <span x-text=\"message.content\"></span></div></div></template></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = MainLayout("anon-chat").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
