// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			templ_7745c5c3_Err = Navbar().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <main class=\"h-[90vh] flex flex-col justify-center items-center\"><div x-data=\"{username: &#39;&#39;}\" class=\"flex flex-col md:flex-row items-center justify-center gap-14\"><form hx-post=\"/api/rooms/create-and-connect\" hx-swap=\"none\" class=\"max-w-[80vw] flex flex-col gap-3 p-5 border-2 border-primary rounded\"><h1 class=\"text-center text-3xl text-primary mb-3\">Create Room</h1><input type=\"text\" name=\"username\" x-model=\"username\" placeholder=\"username\" class=\"block text-xl bg-transparent text-center\"> <input type=\"text\" name=\"roomName\" placeholder=\"room name\" class=\"block text-xl bg-transparent text-center\"> <input type=\"submit\" value=\"Create &amp; Join\" class=\"block text-xl m-auto hover:text-primary focus:text-primary\"></form><form hx-post=\"/api/rooms/connect\" hx-swap=\"none\" class=\"max-w-[80vw] flex flex-col gap-3 p-5 border-2 border-primary rounded\"><h1 class=\"text-center text-3xl text-primary mb-3\">Connect Room</h1><input type=\"text\" name=\"username\" x-model=\"username\" placeholder=\"username\" class=\"block text-xl bg-transparent text-center\"> <input type=\"text\" name=\"roomId\" placeholder=\"roomId\" class=\"block text-xl bg-transparent text-center\"> <input type=\"submit\" value=\"Join\" class=\"block text-xl m-auto hover:text-primary focus:text-primary\"></form></div><div id=\"error-msg\" hx-swap-oob=\"true\" class=\"mt-5\"></div></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = MainLayout("anon-chat").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
